#!/usr/bin/python
#
# map_country.py
#
# written by Tyler W. Davis
# Imperial College London
#
# 2013-08-23 -- created
# 2014-12-11 -- last updated
# 
# ------------
# description:
# ------------
# This script holds two functions for mapping country names or country IDs to 
# continents for the purposes of producing part of the GePiSaT meta-data fields:
# 1. mapid :: two-character identifier for continent
# 2. map :: name of continent
# 3. countryid :: two-character identifier for country
# 4. country :: name of country
#
# ------
# notes:
# ------
# 1. based on previous work "wuGetMeta.pl" 2013/05/31
# 2. country codes identified by ISO 3166
#    http://www.iso.org/iso/country_codes
#
# ----------
# changelog:
# ----------
# 01. created [13.08.23]
# 02. updated doc strings [14.11.27]
# 04. general housekeeping [14.12.11]
#
###############################################################################
## IMPORT MODULES:
###############################################################################
import re

################################################################################
## FUNCTIONS:
################################################################################
def meta_from_country(country):
    """
    Name:     meta_from_country
    Input:    str, country name (country)
    Output:   str, 
    Features: Returns the countinent ID, continent name, country ID, and 
              country name based on a given country name
    """
    # Define dictionary:
    country_dict = {
        'Angola' : 'AF,Africa,AO,Angola',
        'Burkina Faso' : 'AF,Africa,BF,Burkina Faso',
        'Burundi' : 'AF,Africa,BI,Burundi',
        'Benin' : 'AF,Africa,BJ,Benin',
        'Botswana' : 'AF,Africa,BW,Botswana',
        'Zaire' : 'AF,Africa,CD,Zaire',
        'Dem. Republic of the Congo' : 'AF,Africa,CD,Dem. Republic of the Congo',
        'Republic of Congo' : 'AF,Africa,CD,Republic of Congo',
        'Central African Republic' : 'AF,Africa,CF,Central African Republic',
        'Congo' : 'AF,Africa,CG,Congo',
        'Ivory Coast' : 'AF,Africa,CI,Ivory Coast',
        'Cameroon' : 'AF,Africa,CM,Cameroon',
        'Cape Verde Islands' : 'AF,Africa,CV,Cape Verde Islands',
        'Djibouti' : 'AF,Africa,DJ,Djibouti',
        'Algeria' : 'AF,Africa,DZ,Algeria',
        'Egypt' : 'AF,Africa,EG,Egypt',
        'Western Sahara' : 'AF,Africa,EH,Western Sahara',
        'Eritrea' : 'AF,Africa,ER,Eritrea',
        'Ethiopia' : 'AF,Africa,ET,Ethiopia',
        'Gabon Republic' : 'AF,Africa,GA,Gabon Republic',
        'Ghana' : 'AF,Africa,GH,Ghana',
        'Gambia' : 'AF,Africa,GM,Gambia',
        'Guinea' : 'AF,Africa,GN,Guinea',
        'Equatorial Guinea' : 'AF,Africa,GQ,Equatorial Guinea',
        'Guinea-Bissau' : 'AF,Africa,GW,Guinea-Bissau',
        'Kenya' : 'AF,Africa,KE,Kenya',
        'Comoros' : 'AF,Africa,KM,Comoros',
        'Liberia' : 'AF,Africa,LR,Liberia',
        'Lesotho' : 'AF,Africa,LS,Lesotho',
        'Libya' : 'AF,Africa,LY,Libya',
        'Morocco' : 'AF,Africa,MA,Morocco',
        'Madagascar' : 'AF,Africa,MG,Madagascar',
        'Mali Republic' : 'AF,Africa,ML,Mali Republic',
        'Mauritania' : 'AF,Africa,MR,Mauritania',
        'Mauritius' : 'AF,Africa,MU,Mauritius',
        'Malawi' : 'AF,Africa,MW,Malawi',
        'Mozambique' : 'AF,Africa,MZ,Mozambique',
        'Namibia' : 'AF,Africa,NA,Namibia',
        'Niger Republic' : 'AF,Africa,NE,Niger Republic',
        'Nigeria' : 'AF,Africa,NG,Nigeria',
        'Reunion Island' : 'AF,Africa,RE,Reunion Island',
        'Rwanda' : 'AF,Africa,RW,Rwanda',
        'Seychelles' : 'AF,Africa,SC,Seychelles',
        'Sudan' : 'AF,Africa,SD,Sudan',
        'Ascension' : 'AF,Africa,SH,Ascension',
        'St. Helena' : 'AF,Africa,SH,St. Helena',
        'Saint Helena' : 'AF,Africa,SH,Saint Helena',
        'Sierra Leone' : 'AF,Africa,SL,Sierra Leone',
        'Senegal Republic' : 'AF,Africa,SN,Senegal Republic',
        'Somalia Republic' : 'AF,Africa,SO,Somalia Republic',
        'South Sudan' : 'AF,Africa,SS,South Sudan',
        'Principe' : 'AF,Africa,ST,Principe',
        'Sao Tome' : 'AF,Africa,ST,Sao Tome',
        'Swaziland' : 'AF,Africa,SZ,Swaziland',
        'Chad Republic' : 'AF,Africa,TD,Chad Republic',
        'Togo' : 'AF,Africa,TG,Togo',
        'Tunisia' : 'AF,Africa,TN,Tunisia',
        'Tanzania' : 'AF,Africa,TZ,Tanzania',
        'Zanzibar' : 'AF,Africa,TZ,Zanzibar',
        'Uganda' : 'AF,Africa,UG,Uganda',
        'Mayotte Island' : 'AF,Africa,YT,Mayotte Island',
        'South Africa' : 'AF,Africa,ZA,South Africa',
        'Zambia' : 'AF,Africa,ZM,Zambia',
        'Zimbabwe' : 'AF,Africa,ZW,Zimbabwe',
        'Antarctica' : 'AN,Antarctica,AQ,Antarctica',
        'Bouvet Island' : 'AN,Antarctica,BV,Bouvet Island',
        'South Georgia' : 'AN,Antarctica,GS,South Georgia',
        'South Sandwich Islands' : 'AN,Antarctica,GS,South Sandwich Islands',
        'Heard Island' : 'AN,Antarctica,HM,Heard Island',
        'McDonald Islands' : 'AN,Antarctica,HM,McDonald Islands',
        'French Southern Territories' : 'AN,Antarctica,TF,French Southern Territories',
        'United Arab Emirates' : 'AS,Asia,AE,United Arab Emirates',
        'Afghanistan' : 'AS,Asia,AF,Afghanistan',
        'Armenia' : 'AS,Asia,AM,Armenia',
        'Azerbaijan' : 'AS,Asia,AZ,Azerbaijan',
        'Bangladesh' : 'AS,Asia,BD,Bangladesh',
        'Bahrain' : 'AS,Asia,BH,Bahrain',
        'Brunei' : 'AS,Asia,BN,Brunei',
        'Bhutan' : 'AS,Asia,BT,Bhutan',
        'Cocos Islands' : 'AS,Asia,CC,Cocos Islands',
        'China' : 'AS,Asia,CN,China',
        'Christmas Island' : 'AS,Asia,CX,Christmas Island',
        'Georgia' : 'AS,Asia,GE,Georgia',
        'Hong Kong' : 'AS,Asia,HK,Hong Kong',
        'Indonesia' : 'AS,Asia,ID,Indonesia',
        'Israel' : 'AS,Asia,IL,Israel',
        'India' : 'AS,Asia,IN,India',
        'Diego Garcia' : 'AS,Asia,IO,Diego Garcia',
        'Iraq' : 'AS,Asia,IQ,Iraq',
        'Iran' : 'AS,Asia,IR,Iran',
        'Jordan' : 'AS,Asia,JO,Jordan',
        'Japan' : 'AS,Asia,JP,Japan',
        'Kyrgyzstan' : 'AS,Asia,KG,Kyrgyzstan',
        'Cambodia' : 'AS,Asia,KH,Cambodia',
        'North Korea' : 'AS,Asia,KP,North Korea',
        'Peoples Republic of Korea' : 'AS,Asia,KP,Peoples Republic of Korea',
        'South Korea' : 'AS,Asia,KR,South Korea',
        'Republic of Korea' : 'AS,Asia,KR,Republic of Korea',
        'Kuwait' : 'AS,Asia,KW,Kuwait',
        'Kazakhstan' : 'AS,Asia,KZ,Kazakhstan',
        'Laos' : 'AS,Asia,LA,Laos',
        'Lebanon' : 'AS,Asia,LB,Lebanon',
        'Sri Lanka' : 'AS,Asia,LK,Sri Lanka',
        'Myanmar' : 'AS,Asia,MM,Myanmar',
        'Mongolia' : 'AS,Asia,MN,Mongolia',
        'Macau' : 'AS,Asia,MO,Macau',
        'Maldives' : 'AS,Asia,MV,Maldives',
        'Malaysia' : 'AS,Asia,MY,Malaysia',
        'Nepal' : 'AS,Asia,NP,Nepal',
        'Oman' : 'AS,Asia,OM,Oman',
        'Philippines' : 'AS,Asia,PH,Philippines',
        'Pakistan' : 'AS,Asia,PK,Pakistan',
        'Palestine' : 'AS,Asia,PS,Palestine',
        'Qatar' : 'AS,Asia,QA,Qatar',
        'Saudi Arabia' : 'AS,Asia,SA,Saudi Arabia',
        'Singapore' : 'AS,Asia,SG,Singapore',
        'Syria' : 'AS,Asia,SY,Syria',
        'Thailand' : 'AS,Asia,TH,Thailand',
        'Tajikistan' : 'AS,Asia,TJ,Tajikistan',
        'Turkmenistan' : 'AS,Asia,TM,Turkmenistan',
        'Turkey' : 'AS,Asia,TR,Turkey',
        'Taiwan' : 'AS,Asia,TW,Taiwan',
        'Uzbekistan' : 'AS,Asia,UZ,Uzbekistan',
        'Vietnam' : 'AS,Asia,VN,Vietnam',
        'Yemen' : 'AS,Asia,YE,Yemen',
        'Andorra' : 'EU,Europe,AD,Andorra',
        'Albania' : 'EU,Europe,AL,Albania',
        'Austria' : 'EU,Europe,AT,Austria',
        'Aland Islands' : 'EU,Europe,AX,Aland Islands',
        'Bosnia and Herzegovina' : 'EU,Europe,BA,Bosnia and Herzegovina',
        'Belgium' : 'EU,Europe,BE,Belgium',
        'Bulgaria' : 'EU,Europe,BG,Bulgaria',
        'Belarus' : 'EU,Europe,BY,Belarus',
        'Switzerland' : 'EU,Europe,CH,Switzerland',
        'Cyprus' : 'EU,Europe,CY,Cyprus',
        'Czech Republic' : 'EU,Europe,CZ,Czech Republic',
        'Germany' : 'EU,Europe,DE,Germany',
        'Denmark' : 'EU,Europe,DK,Denmark',
        'Estonia' : 'EU,Europe,EE,Estonia',
        'Spain' : 'EU,Europe,ES,Spain',
        'Finland' : 'EU,Europe,FI,Finland',
        'Faroe Islands' : 'EU,Europe,FO,Faroe Islands',
        'France' : 'EU,Europe,FR,France',
        'United Kingdom' : 'EU,Europe,GB,United Kingdom',
        'Gibraltar' : 'EU,Europe,GI,Gibraltar',
        'Greece' : 'EU,Europe,GR,Greece',
        'Croatia' : 'EU,Europe,HR,Croatia',
        'Hungary' : 'EU,Europe,HU,Hungary',
        'Ireland' : 'EU,Europe,IE,Ireland',
        'Isle of Man' : 'EU,Europe,IM,Isle of Man',
        'Iceland' : 'EU,Europe,IS,Iceland',
        'Italy' : 'EU,Europe,IT,Italy',
        'Guernsey' : 'EU,Europe,GG,Guernsey',
        'Jersey' : 'EU,Europe,JE,Jersey',
        'Liechtenstein' : 'EU,Europe,LI,Liechtenstein',
        'Lithuania' : 'EU,Europe,LT,Lithuania',
        'Luxembourg' : 'EU,Europe,LU,Luxembourg',
        'Latvia' : 'EU,Europe,LV,Latvia',
        'Monaco' : 'EU,Europe,MC,Monaco',
        'Moldova' : 'EU,Europe,MD,Moldova',
        'Montenegro' : 'EU,Europe,ME,Montenegro',
        'Macedonia' : 'EU,Europe,MK,Macedonia',
        'Malta' : 'EU,Europe,MT,Malta',
        'Netherlands' : 'EU,Europe,NL,Netherlands',
        'Norway' : 'EU,Europe,NO,Norway',
        'Poland' : 'EU,Europe,PL,Poland',
        'Portugal' : 'EU,Europe,PT,Portugal',
        'Romania' : 'EU,Europe,RO,Romania',
        'Serbia' : 'EU,Europe,RS,Serbia',
        'Yugoslavia' : 'EU,Europe,RS,Yugoslavia',
        'Kosovo' : 'EU,Europe,RS,Kosovo',
        'Russia' : 'EU,Europe,RU,Russia',
        'Sweden' : 'EU,Europe,SE,Sweden',
        'Slovenia' : 'EU,Europe,SI,Slovenia',
        'Svalbard and Jan Mayen' : 'EU,Europe,SJ,Svalbard and Jan Mayen',
        'Slovakia' : 'EU,Europe,SK,Slovakia',
        'San Marino' : 'EU,Europe,SM,San Marino',
        'Ukraine' : 'EU,Europe,UA,Ukraine',
        'Vatican city' : 'EU,Europe,VA,Vatican city',
        'Antigua and Barbuda' : 'NA,North America,AG,Antigua and Barbuda',
        'Anguilla' : 'NA,North America,AI,Anguilla',
        'Aruba' : 'NA,North America,AW,Aruba',
        'Barbados' : 'NA,North America,BB,Barbados',
        'Bermuda' : 'NA,North America,BM,Bermuda',
        'Bahamas' : 'NA,North America,BS,Bahamas',
        'Belize' : 'NA,North America,BZ,Belize',
        'Canada' : 'NA,North America,CA,Canada',
        'Costa Rica' : 'NA,North America,CR,Costa Rica',
        'Cuba' : 'NA,North America,CU,Cuba',
        'Curacao' : 'NA,North America,CW,Curacao',
        'Netherlands Antilles' : 'NA,North America,CW,Netherlands Antilles',
        'Dominica' : 'NA,North America,DM,Dominica',
        'Dominican Republic' : 'NA,North America,DO,Dominican Republic',
        'Grenada' : 'NA,North America,GD,Grenada',
        'Grenada and Carriacuou' : 'NA,North America,GD,Grenada and Carriacuou',
        'Greenland' : 'NA,North America,GL,Greenland',
        'Guadeloupe' : 'NA,North America,GP,Guadeloupe',
        'Guatemala' : 'NA,North America,GT,Guatemala',
        'Honduras' : 'NA,North America,HN,Honduras',
        'Haiti' : 'NA,North America,HT,Haiti',
        'Jamaica' : 'NA,North America,JM,Jamaica',
        'Nevis' : 'NA,North America,KN,Nevis',
        'St. Kitts' : 'NA,North America,KN,St. Kitts',
        'Saint Kitts' : 'NA,North America,KN,Saint Kitts',
        'Cayman Islands' : 'NA,North America,KY,Cayman Islands',
        'St. Lucia' : 'NA,North America,LC,St. Lucia',
        'Saint Lucia' : 'NA,North America,LC,Saint Lucia',
        'Martinique' : 'NA,North America,MQ,Martinique',
        'Montserrat' : 'NA,North America,MS,Montserrat',
        'Mexico' : 'NA,North America,MX,Mexico',
        'Nicaragua' : 'NA,North America,NI,Nicaragua',
        'Panama' : 'NA,North America,PA,Panama',
        'Miquelon' : 'NA,North America,PM,Miquelon',
        'St. Pierre and Miquelon' : 'NA,North America,PM,St. Pierre and Miquelon',
        'Saint Pierre and Miquelon' : 'NA,North America,PM,Saint Pierre and Miquelon',
        'Puerto Rico' : 'NA,North America,PR,Puerto Rico',
        'El Salvador' : 'NA,North America,SV,El Salvador',
        'Sint Maarten' : 'NA,North America,SX,Sint Maarten',
        'Turks and Caicos Islands' : 'NA,North America,TC,Turks and Caicos Islands',
        'Trinidad and Tobago' : 'NA,North America,TT,Trinidad and Tobago',
        'United States' : 'NA,North America,US,United States',
        'St. Vincent' : 'NA,North America,VC,St. Vincent',
        'Saint Vincent' : 'NA,North America,VC,Saint Vincent',
        'British Virgin Islands' : 'NA,North America,VG,British Virgin Islands',
        'US Virgin Islands' : 'NA,North America,VI,US Virgin Islands',
        'American Samoa' : 'OC,Oceania,AS,American Samoa',
        'Australia' : 'OC,Oceania,AU,Australia',
        'Cook Islands' : 'OC,Oceania,CK,Cook Islands',
        'Fiji Islands' : 'OC,Oceania,FJ,Fiji Islands',
        'Federated States of Micronesia' : 'OC,Oceania,FM,Federated States of Micronesia',
        'Guam' : 'OC,Oceania,GU,Guam',
        'Kiribati' : 'OC,Oceania,KI,Kiribati',
        'Marshall Islands' : 'OC,Oceania,MH,Marshall Islands',
        'Mariana Islands' : 'OC,Oceania,MP,Mariana Islands',
        'Saipan' : 'OC,Oceania,MP,Saipan',
        'New Caledonia' : 'OC,Oceania,NC,New Caledonia',
        'Norfolk Island' : 'OC,Oceania,NF,Norfolk Island',
        'Nauru' : 'OC,Oceania,NR,Nauru',
        'Niue' : 'OC,Oceania,NU,Niue',
        'Chatham Island' : 'OC,Oceania,NZ,Chatham Island',
        'New Zealand' : 'OC,Oceania,NZ,New Zealand',
        'French Polynesia' : 'OC,Oceania,PF,French Polynesia',
        'Papua New Guinea' : 'OC,Oceania,PG,Papua New Guinea',
        'Palau' : 'OC,Oceania,PW,Palau',
        'Solomon Islands' : 'OC,Oceania,SB,Solomon Islands',
        'Tokelau' : 'OC,Oceania,TK,Tokelau',
        'East Timor' : 'OC,Oceania,TL,East Timor',
        'Timor-Leste' : 'OC,Oceania,TL,Timor-Leste',
        'Tonga' : 'OC,Oceania,TO,Tonga',
        'Tuvalu' : 'OC,Oceania,TV,Tuvalu',
        'Midway Islands' : 'OC,Oceania,UM,Midway Islands',
        'Wake Island' : 'OC,Oceania,UM,Wake Island',
        'Vanuatu' : 'OC,Oceania,VU,Vanuatu',
        'Wallis and Futuna Islands' : 'OC,Oceania,WF,Wallis and Futuna Islands',
        'Samoa' : 'OC,Oceania,WS,Samoa',
        'Argentina' : 'SA,South America,AR,Argentina',
        'Bolivia' : 'SA,South America,BO,Bolivia',
        'Brazil' : 'SA,South America,BR,Brazil',
        'Chile' : 'SA,South America,CL,Chile',
        'Colombia' : 'SA,South America,CO,Colombia',
        'Ecuador' : 'SA,South America,EC,Ecuador',
        'Falkland Islands' : 'SA,South America,FK,Falkland Islands',
        'French Guiana' : 'SA,South America,GF,French Guiana',
        'Guiana' : 'SA,South America,GY,Guiana',
        'Guyana' : 'SA,South America,GY,Guyana',
        'Peru' : 'SA,South America,PE,Peru',
        'Paraguay' : 'SA,South America,PY,Paraguay',
        'Suriname' : 'SA,South America,SR,Suriname',
        'Uruguay' : 'SA,South America,UY,Uruguay',
        'Venezuela' : 'SA,South America,VE,Venezuela'
        }
    #
    # Check to see if country is listed:
    list_val = ''
    if country in country_dict.keys():
        list_val = country_dict[country]
    else:
        # Test to see if country is abbreviated in the list above
        # NOTE: may fail to return correct value, e.g., Republic of Korea v.
        #       Peoples Republic of Korea
        for c in country_dict.keys():
            if re.search(country, c):
                list_val = country_dict[c]
                #
    #
    return list_val
#
def meta_from_countryid(countryid):
    """
    Features: Get meta data based on country ID
    """
    # Define dictionary:
    # NOTE: some countryids are associated with more than one country (name)
    #       duplicates have been commented out (change as appropriate)
    countryid_dict = {
        'AO' : 'AF,Africa,AO,Angola',
        'BF' : 'AF,Africa,BF,Burkina Faso',
        'BI' : 'AF,Africa,BI,Burundi',
        'BJ' : 'AF,Africa,BJ,Benin',
        'BW' : 'AF,Africa,BW,Botswana',
        #'CD' : 'AF,Africa,CD,Zaire',
        'CD' : 'AF,Africa,CD,Dem. Republic of the Congo',
        #'CD' : 'AF,Africa,CD,Republic of Congo',
        'CF' : 'AF,Africa,CF,Central African Republic',
        'CG' : 'AF,Africa,CG,Congo',
        'CI' : 'AF,Africa,CI,Ivory Coast',
        'CM' : 'AF,Africa,CM,Cameroon',
        'CV' : 'AF,Africa,CV,Cape Verde Islands',
        'DJ' : 'AF,Africa,DJ,Djibouti',
        'DZ' : 'AF,Africa,DZ,Algeria',
        'EG' : 'AF,Africa,EG,Egypt',
        'EH' : 'AF,Africa,EH,Western Sahara',
        'ER' : 'AF,Africa,ER,Eritrea',
        'ET' : 'AF,Africa,ET,Ethiopia',
        'GA' : 'AF,Africa,GA,Gabon Republic',
        'GH' : 'AF,Africa,GH,Ghana',
        'GM' : 'AF,Africa,GM,Gambia',
        'GN' : 'AF,Africa,GN,Guinea',
        'GQ' : 'AF,Africa,GQ,Equatorial Guinea',
        'GW' : 'AF,Africa,GW,Guinea-Bissau',
        'KE' : 'AF,Africa,KE,Kenya',
        'KM' : 'AF,Africa,KM,Comoros',
        'LR' : 'AF,Africa,LR,Liberia',
        'LS' : 'AF,Africa,LS,Lesotho',
        'LY' : 'AF,Africa,LY,Libya',
        'MA' : 'AF,Africa,MA,Morocco',
        'MG' : 'AF,Africa,MG,Madagascar',
        'ML' : 'AF,Africa,ML,Mali Republic',
        'MR' : 'AF,Africa,MR,Mauritania',
        'MU' : 'AF,Africa,MU,Mauritius',
        'MW' : 'AF,Africa,MW,Malawi',
        'MZ' : 'AF,Africa,MZ,Mozambique',
        'NA' : 'AF,Africa,NA,Namibia',
        'NE' : 'AF,Africa,NE,Niger Republic',
        'NG' : 'AF,Africa,NG,Nigeria',
        'RE' : 'AF,Africa,RE,Reunion Island',
        'RW' : 'AF,Africa,RW,Rwanda',
        'SC' : 'AF,Africa,SC,Seychelles',
        'SD' : 'AF,Africa,SD,Sudan',
        #'SH' : 'AF,Africa,SH,Ascension',
        'SH' : 'AF,Africa,SH,St. Helena',
        #'SH' : 'AF,Africa,SH,Saint Helena',
        'SL' : 'AF,Africa,SL,Sierra Leone',
        'SN' : 'AF,Africa,SN,Senegal Republic',
        'SO' : 'AF,Africa,SO,Somalia Republic',
        'SS' : 'AF,Africa,SS,South Sudan',
        #'ST' : 'AF,Africa,ST,Principe',
        'ST' : 'AF,Africa,ST,Sao Tome',
        'SZ' : 'AF,Africa,SZ,Swaziland',
        'TD' : 'AF,Africa,TD,Chad Republic',
        'TG' : 'AF,Africa,TG,Togo',
        'TN' : 'AF,Africa,TN,Tunisia',
        'TZ' : 'AF,Africa,TZ,Tanzania',
        #'TZ' : 'AF,Africa,TZ,Zanzibar',
        'UG' : 'AF,Africa,UG,Uganda',
        'YT' : 'AF,Africa,YT,Mayotte Island',
        'ZA' : 'AF,Africa,ZA,South Africa',
        'ZM' : 'AF,Africa,ZM,Zambia',
        'ZW' : 'AF,Africa,ZW,Zimbabwe',
        'AQ' : 'AN,Antarctica,AQ,Antarctica',
        'BV' : 'AN,Antarctica,BV,Bouvet Island',
        'GS' : 'AN,Antarctica,GS,South Georgia',
        #'GS' : 'AN,Antarctica,GS,South Sandwich Islands',
        'HM' : 'AN,Antarctica,HM,Heard Island',
        #'HM' : 'AN,Antarctica,HM,McDonald Islands',
        'TF' : 'AN,Antarctica,TF,French Southern Territories',
        'AE' : 'AS,Asia,AE,United Arab Emirates',
        'AF' : 'AS,Asia,AF,Afghanistan',
        'AM' : 'AS,Asia,AM,Armenia',
        'AZ' : 'AS,Asia,AZ,Azerbaijan',
        'BD' : 'AS,Asia,BD,Bangladesh',
        'BH' : 'AS,Asia,BH,Bahrain',
        'BN' : 'AS,Asia,BN,Brunei',
        'BT' : 'AS,Asia,BT,Bhutan',
        'CC' : 'AS,Asia,CC,Cocos Islands',
        'CN' : 'AS,Asia,CN,China',
        'CX' : 'AS,Asia,CX,Christmas Island',
        'GE' : 'AS,Asia,GE,Georgia',
        'HK' : 'AS,Asia,HK,Hong Kong',
        'ID' : 'AS,Asia,ID,Indonesia',
        'IL' : 'AS,Asia,IL,Israel',
        'IN' : 'AS,Asia,IN,India',
        'IO' : 'AS,Asia,IO,Diego Garcia',
        'IQ' : 'AS,Asia,IQ,Iraq',
        'IR' : 'AS,Asia,IR,Iran',
        'JO' : 'AS,Asia,JO,Jordan',
        'JP' : 'AS,Asia,JP,Japan',
        'KG' : 'AS,Asia,KG,Kyrgyzstan',
        'KH' : 'AS,Asia,KH,Cambodia',
        #'KP' : 'AS,Asia,KP,North Korea',
        'KP' : 'AS,Asia,KP,Peoples Republic of Korea',
        #'KR' : 'AS,Asia,KR,South Korea',
        'KR' : 'AS,Asia,KR,Republic of Korea',
        'KW' : 'AS,Asia,KW,Kuwait',
        'KZ' : 'AS,Asia,KZ,Kazakhstan',
        'LA' : 'AS,Asia,LA,Laos',
        'LB' : 'AS,Asia,LB,Lebanon',
        'LK' : 'AS,Asia,LK,Sri Lanka',
        'MM' : 'AS,Asia,MM,Myanmar',
        #'MN' : 'AS,Asia,MN,Mongolia',
        'MO' : 'AS,Asia,MO,Macau',
        'MV' : 'AS,Asia,MV,Maldives',
        'MY' : 'AS,Asia,MY,Malaysia',
        'NP' : 'AS,Asia,NP,Nepal',
        'OM' : 'AS,Asia,OM,Oman',
        'PH' : 'AS,Asia,PH,Philippines',
        'PK' : 'AS,Asia,PK,Pakistan',
        'PS' : 'AS,Asia,PS,Palestine',
        'QA' : 'AS,Asia,QA,Qatar',
        'SA' : 'AS,Asia,SA,Saudi Arabia',
        'SG' : 'AS,Asia,SG,Singapore',
        'SY' : 'AS,Asia,SY,Syria',
        'TH' : 'AS,Asia,TH,Thailand',
        'TJ' : 'AS,Asia,TJ,Tajikistan',
        'TM' : 'AS,Asia,TM,Turkmenistan',
        'TR' : 'AS,Asia,TR,Turkey',
        'TW' : 'AS,Asia,TW,Taiwan',
        'UZ' : 'AS,Asia,UZ,Uzbekistan',
        'VN' : 'AS,Asia,VN,Vietnam',
        'YE' : 'AS,Asia,YE,Yemen',
        'AD' : 'EU,Europe,AD,Andorra',
        'AL' : 'EU,Europe,AL,Albania',
        'AT' : 'EU,Europe,AT,Austria',
        'AX' : 'EU,Europe,AX,Aland Islands',
        'BA' : 'EU,Europe,BA,Bosnia and Herzegovina',
        'BE' : 'EU,Europe,BE,Belgium',
        'BG' : 'EU,Europe,BG,Bulgaria',
        'BY' : 'EU,Europe,BY,Belarus',
        'CH' : 'EU,Europe,CH,Switzerland',
        'CY' : 'EU,Europe,CY,Cyprus',
        'CZ' : 'EU,Europe,CZ,Czech Republic',
        'DE' : 'EU,Europe,DE,Germany',
        'DK' : 'EU,Europe,DK,Denmark',
        'EE' : 'EU,Europe,EE,Estonia',
        'ES' : 'EU,Europe,ES,Spain',
        'FI' : 'EU,Europe,FI,Finland',
        'FO' : 'EU,Europe,FO,Faroe Islands',
        'FR' : 'EU,Europe,FR,France',
        'GB' : 'EU,Europe,GB,United Kingdom',
        'GI' : 'EU,Europe,GI,Gibraltar',
        'GR' : 'EU,Europe,GR,Greece',
        'HR' : 'EU,Europe,HR,Croatia',
        'HU' : 'EU,Europe,HU,Hungary',
        'IE' : 'EU,Europe,IE,Ireland',
        'IM' : 'EU,Europe,IM,Isle of Man',
        'IS' : 'EU,Europe,IS,Iceland',
        'IT' : 'EU,Europe,IT,Italy',
        'GG' : 'EU,Europe,GG,Guernsey',
        'JE' : 'EU,Europe,JE,Jersey',
        'LI' : 'EU,Europe,LI,Liechtenstein',
        'LT' : 'EU,Europe,LT,Lithuania',
        'LU' : 'EU,Europe,LU,Luxembourg',
        'LV' : 'EU,Europe,LV,Latvia',
        'MC' : 'EU,Europe,MC,Monaco',
        'MD' : 'EU,Europe,MD,Moldova',
        'ME' : 'EU,Europe,ME,Montenegro',
        'MK' : 'EU,Europe,MK,Macedonia',
        'MT' : 'EU,Europe,MT,Malta',
        'NL' : 'EU,Europe,NL,Netherlands',
        'NO' : 'EU,Europe,NO,Norway',
        'PL' : 'EU,Europe,PL,Poland',
        'PT' : 'EU,Europe,PT,Portugal',
        'RO' : 'EU,Europe,RO,Romania',
        #'RS' : 'EU,Europe,RS,Serbia',
        'RS' : 'EU,Europe,RS,Yugoslavia',
        #'RS' : 'EU,Europe,RS,Kosovo',
        'RU' : 'EU,Europe,RU,Russia',
        'SE' : 'EU,Europe,SE,Sweden',
        'SI' : 'EU,Europe,SI,Slovenia',
        'SJ' : 'EU,Europe,SJ,Svalbard and Jan Mayen',
        'SK' : 'EU,Europe,SK,Slovakia',
        'SM' : 'EU,Europe,SM,San Marino',
        'UA' : 'EU,Europe,UA,Ukraine',
        'VA' : 'EU,Europe,VA,Vatican city',
        'AG' : 'NA,North America,AG,Antigua and Barbuda',
        'AI' : 'NA,North America,AI,Anguilla',
        'AW' : 'NA,North America,AW,Aruba',
        'BB' : 'NA,North America,BB,Barbados',
        'BM' : 'NA,North America,BM,Bermuda',
        'BS' : 'NA,North America,BS,Bahamas',
        'BZ' : 'NA,North America,BZ,Belize',
        'CA' : 'NA,North America,CA,Canada',
        'CR' : 'NA,North America,CR,Costa Rica',
        'CU' : 'NA,North America,CU,Cuba',
        #'CW' : 'NA,North America,CW,Curacao',
        'CW' : 'NA,North America,CW,Netherlands Antilles',
        'DM' : 'NA,North America,DM,Dominica',
        'DO' : 'NA,North America,DO,Dominican Republic',
        #'GD' : 'NA,North America,GD,Grenada',
        'GD' : 'NA,North America,GD,Grenada and Carriacuou',
        'GL' : 'NA,North America,GL,Greenland',
        'GP' : 'NA,North America,GP,Guadeloupe',
        'GT' : 'NA,North America,GT,Guatemala',
        'HN' : 'NA,North America,HN,Honduras',
        'HT' : 'NA,North America,HT,Haiti',
        'JM' : 'NA,North America,JM,Jamaica',
        #'KN' : 'NA,North America,KN,Nevis',
        #'KN' : 'NA,North America,KN,St. Kitts',
        'KN' : 'NA,North America,KN,Saint Kitts',
        'KY' : 'NA,North America,KY,Cayman Islands',
        #'LC' : 'NA,North America,LC,St. Lucia',
        'LC' : 'NA,North America,LC,Saint Lucia',
        'MQ' : 'NA,North America,MQ,Martinique',
        'MS' : 'NA,North America,MS,Montserrat',
        'MX' : 'NA,North America,MX,Mexico',
        'NI' : 'NA,North America,NI,Nicaragua',
        'PA' : 'NA,North America,PA,Panama',
        #'PM' : 'NA,North America,PM,Miquelon',
        #'PM' : 'NA,North America,PM,St. Pierre and Miquelon',
        'PM' : 'NA,North America,PM,Saint Pierre and Miquelon',
        'PR' : 'NA,North America,PR,Puerto Rico',
        'SV' : 'NA,North America,SV,El Salvador',
        'SX' : 'NA,North America,SX,Sint Maarten',
        'TC' : 'NA,North America,TC,Turks and Caicos Islands',
        'TT' : 'NA,North America,TT,Trinidad and Tobago',
        'US' : 'NA,North America,US,United States',
        #'VC' : 'NA,North America,VC,St. Vincent',
        'VC' : 'NA,North America,VC,Saint Vincent',
        'VG' : 'NA,North America,VG,British Virgin Islands',
        'VI' : 'NA,North America,VI,US Virgin Islands',
        'AS' : 'OC,Oceania,AS,American Samoa',
        'AU' : 'OC,Oceania,AU,Australia',
        'CK' : 'OC,Oceania,CK,Cook Islands',
        'FJ' : 'OC,Oceania,FJ,Fiji Islands',
        'FM' : 'OC,Oceania,FM,Federated States of Micronesia',
        'GU' : 'OC,Oceania,GU,Guam',
        'KI' : 'OC,Oceania,KI,Kiribati',
        'MH' : 'OC,Oceania,MH,Marshall Islands',
        'MP' : 'OC,Oceania,MP,Mariana Islands',
        #'MP' : 'OC,Oceania,MP,Saipan',
        'NC' : 'OC,Oceania,NC,New Caledonia',
        'NF' : 'OC,Oceania,NF,Norfolk Island',
        'NR' : 'OC,Oceania,NR,Nauru',
        'NU' : 'OC,Oceania,NU,Niue',
        #'NZ' : 'OC,Oceania,NZ,Chatham Island',
        'NZ' : 'OC,Oceania,NZ,New Zealand',
        'PF' : 'OC,Oceania,PF,French Polynesia',
        'PG' : 'OC,Oceania,PG,Papua New Guinea',
        'PW' : 'OC,Oceania,PW,Palau',
        'SB' : 'OC,Oceania,SB,Solomon Islands',
        'TK' : 'OC,Oceania,TK,Tokelau',
        #'TL' : 'OC,Oceania,TL,East Timor',
        'TL' : 'OC,Oceania,TL,Timor-Leste',
        'TO' : 'OC,Oceania,TO,Tonga',
        'TV' : 'OC,Oceania,TV,Tuvalu',
        'UM' : 'OC,Oceania,UM,Midway Islands',
        #'UM' : 'OC,Oceania,UM,Wake Island',
        'VU' : 'OC,Oceania,VU,Vanuatu',
        'WF' : 'OC,Oceania,WF,Wallis and Futuna Islands',
        'WS' : 'OC,Oceania,WS,Samoa',
        'AR' : 'SA,South America,AR,Argentina',
        'BO' : 'SA,South America,BO,Bolivia',
        'BR' : 'SA,South America,BR,Brazil',
        'CL' : 'SA,South America,CL,Chile',
        'CO' : 'SA,South America,CO,Colombia',
        'EC' : 'SA,South America,EC,Ecuador',
        'FK' : 'SA,South America,FK,Falkland Islands',
        'GF' : 'SA,South America,GF,French Guiana',
        'GY' : 'SA,South America,GY,Guiana',
        #'GY' : 'SA,South America,GY,Guyana',
        'PE' : 'SA,South America,PE,Peru',
        'PY' : 'SA,South America,PY,Paraguay',
        'SR' : 'SA,South America,SR,Suriname',
        'UY' : 'SA,South America,UY,Uruguay',
        'VE' : 'SA,South America,VE,Venezuela'
        }
    #
    # See if country code is listed:
    list_val = ''
    if countryid.upper() in countryid_dict.keys():
        list_val = countryid_dict[countryid]
        #
    return list_val
